// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: message.grpc.proto

package rest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MessageService_SendWSMessage_FullMethodName      = "/rest.MessageService/SendWSMessage"
	MessageService_GetHistoryMessages_FullMethodName = "/rest.MessageService/GetHistoryMessages"
	MessageService_MessageStream_FullMethodName      = "/rest.MessageService/MessageStream"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	SendWSMessage(ctx context.Context, in *SendWSMessageRequest, opts ...grpc.CallOption) (*SendWSMessageResponse, error)
	// 获取历史消息
	GetHistoryMessages(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// 双向流：Connect服务与Message服务的消息通道
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (MessageService_MessageStreamClient, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendWSMessage(ctx context.Context, in *SendWSMessageRequest, opts ...grpc.CallOption) (*SendWSMessageResponse, error) {
	out := new(SendWSMessageResponse)
	err := c.cc.Invoke(ctx, MessageService_SendWSMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GetHistoryMessages(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, MessageService_GetHistoryMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (MessageService_MessageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], MessageService_MessageStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &messageServiceMessageStreamClient{stream}
	return x, nil
}

type MessageService_MessageStreamClient interface {
	Send(*MessageStreamRequest) error
	Recv() (*MessageStreamResponse, error)
	grpc.ClientStream
}

type messageServiceMessageStreamClient struct {
	grpc.ClientStream
}

func (x *messageServiceMessageStreamClient) Send(m *MessageStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageServiceMessageStreamClient) Recv() (*MessageStreamResponse, error) {
	m := new(MessageStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	SendWSMessage(context.Context, *SendWSMessageRequest) (*SendWSMessageResponse, error)
	// 获取历史消息
	GetHistoryMessages(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// 双向流：Connect服务与Message服务的消息通道
	MessageStream(MessageService_MessageStreamServer) error
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) SendWSMessage(context.Context, *SendWSMessageRequest) (*SendWSMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendWSMessage not implemented")
}
func (UnimplementedMessageServiceServer) GetHistoryMessages(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoryMessages not implemented")
}
func (UnimplementedMessageServiceServer) MessageStream(MessageService_MessageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_SendWSMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWSMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendWSMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_SendWSMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendWSMessage(ctx, req.(*SendWSMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetHistoryMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetHistoryMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_GetHistoryMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetHistoryMessages(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageServiceServer).MessageStream(&messageServiceMessageStreamServer{stream})
}

type MessageService_MessageStreamServer interface {
	Send(*MessageStreamResponse) error
	Recv() (*MessageStreamRequest, error)
	grpc.ServerStream
}

type messageServiceMessageStreamServer struct {
	grpc.ServerStream
}

func (x *messageServiceMessageStreamServer) Send(m *MessageStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageServiceMessageStreamServer) Recv() (*MessageStreamRequest, error) {
	m := new(MessageStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rest.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWSMessage",
			Handler:    _MessageService_SendWSMessage_Handler,
		},
		{
			MethodName: "GetHistoryMessages",
			Handler:    _MessageService_GetHistoryMessages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageStream",
			Handler:       _MessageService_MessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.grpc.proto",
}
