// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.2
// source: message.grpc.proto

package rest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发消息请求
type SendWSMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *WSMessage `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendWSMessageRequest) Reset() {
	*x = SendWSMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWSMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWSMessageRequest) ProtoMessage() {}

func (x *SendWSMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWSMessageRequest.ProtoReflect.Descriptor instead.
func (*SendWSMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *SendWSMessageRequest) GetMsg() *WSMessage {
	if x != nil {
		return x.Msg
	}
	return nil
}

// 发消息响应
type SendWSMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendWSMessageResponse) Reset() {
	*x = SendWSMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendWSMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWSMessageResponse) ProtoMessage() {}

func (x *SendWSMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWSMessageResponse.ProtoReflect.Descriptor instead.
func (*SendWSMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *SendWSMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendWSMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_message_grpc_proto protoreflect.FileDescriptor

var file_message_grpc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x14, 0x53, 0x65, 0x6e,
	0x64, 0x57, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x57, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x4b, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x53, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0xa3, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x53, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x57, 0x53, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x53, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x72, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x72, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x72, 0x65, 0x73,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_grpc_proto_rawDescOnce sync.Once
	file_message_grpc_proto_rawDescData = file_message_grpc_proto_rawDesc
)

func file_message_grpc_proto_rawDescGZIP() []byte {
	file_message_grpc_proto_rawDescOnce.Do(func() {
		file_message_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_grpc_proto_rawDescData)
	})
	return file_message_grpc_proto_rawDescData
}

var file_message_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_grpc_proto_goTypes = []interface{}{
	(*SendWSMessageRequest)(nil),  // 0: rest.SendWSMessageRequest
	(*SendWSMessageResponse)(nil), // 1: rest.SendWSMessageResponse
	(*WSMessage)(nil),             // 2: rest.WSMessage
	(*GetHistoryRequest)(nil),     // 3: rest.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 4: rest.GetHistoryResponse
}
var file_message_grpc_proto_depIdxs = []int32{
	2, // 0: rest.SendWSMessageRequest.msg:type_name -> rest.WSMessage
	0, // 1: rest.MessageService.SendWSMessage:input_type -> rest.SendWSMessageRequest
	3, // 2: rest.MessageService.GetHistoryMessages:input_type -> rest.GetHistoryRequest
	1, // 3: rest.MessageService.SendWSMessage:output_type -> rest.SendWSMessageResponse
	4, // 4: rest.MessageService.GetHistoryMessages:output_type -> rest.GetHistoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_grpc_proto_init() }
func file_message_grpc_proto_init() {
	if File_message_grpc_proto != nil {
		return
	}
	file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWSMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendWSMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_grpc_proto_goTypes,
		DependencyIndexes: file_message_grpc_proto_depIdxs,
		MessageInfos:      file_message_grpc_proto_msgTypes,
	}.Build()
	File_message_grpc_proto = out.File
	file_message_grpc_proto_rawDesc = nil
	file_message_grpc_proto_goTypes = nil
	file_message_grpc_proto_depIdxs = nil
}
